interface /GICOM/IF_CONST_BIZ_CLASS
  public .


  CONSTANTS GC_BIZ_CLASS_PURCHASE         TYPE /GICOM/BIZ_CLASS VALUE 'P'.
  CONSTANTS GC_BIZ_CLASS_SALES            TYPE /GICOM/BIZ_CLASS VALUE 'S'.
  CONSTANTS GC_BIZ_CLASS_STOCK_TRANSFER   TYPE /GICOM/BIZ_CLASS VALUE 'GM'.
  CONSTANTS GC_BIZ_CLASS_FIXED_AMOUNT     TYPE /GICOM/BIZ_CLASS VALUE 'F'.
  CONSTANTS GC_BIZ_CLASS_M_STLMT_WO_AGRMT TYPE /GICOM/BIZ_CLASS VALUE 'MO'.
  CONSTANTS GC_BIZ_CLASS_MINIMUM          TYPE /GICOM/BIZ_CLASS VALUE 'M'.
  CONSTANTS GC_BIZ_CLASS_MAXIMUM          TYPE /GICOM/BIZ_CLASS VALUE 'MX'.
  CONSTANTS GC_BIZ_CLASS_PREPAYMENT       TYPE /GICOM/BIZ_CLASS VALUE 'PP'.
  CONSTANTS GC_BIZ_CLASS_PARTIAL_STLMT    TYPE /GICOM/BIZ_CLASS VALUE 'PS'.
  CONSTANTS GC_BIZ_CLASS_M_STLMT_DELTA    TYPE /GICOM/BIZ_CLASS VALUE 'MD'.
  CONSTANTS GC_BIZ_CLASS_M_STLMT_WO_CALC  TYPE /GICOM/BIZ_CLASS VALUE 'MC'.
  CONSTANTS GC_BIZ_CLASS_DISTRIBUTION     type /GICOM/BIZ_CLASS VALUE 'D'.
endinterface.
