CLASS /gicom/cl_dso_sale_org_api_s4 DEFINITION
  PUBLIC
  INHERITING FROM /gicom/cl_dso_sales_org
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS /GICOM/CL_DSO_SALE_ORG_API_S4 IMPLEMENTATION.
ENDCLASS.
