*---------------------------------------------------------------------*
*    view related data declarations
*---------------------------------------------------------------------*
*...processing: /GICOM/VMFOLDERT................................*
TABLES: /GICOM/VMFOLDERT, */GICOM/VMFOLDERT. "view work areas
CONTROLS: TCTRL_/GICOM/VMFOLDERT
TYPE TABLEVIEW USING SCREEN '0018'.
DATA: BEGIN OF STATUS_/GICOM/VMFOLDERT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMFOLDERT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMFOLDERT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMFOLDERT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMFOLDERT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMFOLDERT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMFOLDERT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMFOLDERT_TOTAL.

*...processing: /GICOM/VMLVLPROT................................*
TABLES: /GICOM/VMLVLPROT, */GICOM/VMLVLPROT. "view work areas
CONTROLS: TCTRL_/GICOM/VMLVLPROT
TYPE TABLEVIEW USING SCREEN '0016'.
DATA: BEGIN OF STATUS_/GICOM/VMLVLPROT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMLVLPROT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMLVLPROT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMLVLPROT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMLVLPROT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMLVLPROT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMLVLPROT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMLVLPROT_TOTAL.

*...processing: /GICOM/VMNAVANAP................................*
TABLES: /GICOM/VMNAVANAP, */GICOM/VMNAVANAP. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVANAP
TYPE TABLEVIEW USING SCREEN '0006'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVANAP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVANAP.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVANAP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANAP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANAP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVANAP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANAP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANAP_TOTAL.

*...processing: /GICOM/VMNAVANC.................................*
TABLES: /GICOM/VMNAVANC, */GICOM/VMNAVANC. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVANC
TYPE TABLEVIEW USING SCREEN '0001'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVANC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVANC.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVANC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVANC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANC_TOTAL.

*...processing: /GICOM/VMNAVANCA................................*
TABLES: /GICOM/VMNAVANCA, */GICOM/VMNAVANCA. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVANCA
TYPE TABLEVIEW USING SCREEN '0005'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVANCA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVANCA.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVANCA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANCA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANCA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVANCA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANCA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANCA_TOTAL.

*...processing: /GICOM/VMNAVANCT................................*
TABLES: /GICOM/VMNAVANCT, */GICOM/VMNAVANCT. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVANCT
TYPE TABLEVIEW USING SCREEN '0004'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVANCT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVANCT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVANCT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANCT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANCT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVANCT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVANCT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVANCT_TOTAL.

*...processing: /GICOM/VMNAVASS.................................*
TABLES: /GICOM/VMNAVASS, */GICOM/VMNAVASS. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVASS
TYPE TABLEVIEW USING SCREEN '0011'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVASS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVASS.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVASS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVASS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVASS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVASS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVASS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVASS_TOTAL.

*...processing: /GICOM/VMNAVASSP................................*
TABLES: /GICOM/VMNAVASSP, */GICOM/VMNAVASSP. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVASSP
TYPE TABLEVIEW USING SCREEN '0012'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVASSP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVASSP.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVASSP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVASSP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVASSP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVASSP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVASSP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVASSP_TOTAL.

*...processing: /GICOM/VMNAVOBJ.................................*
TABLES: /GICOM/VMNAVOBJ, */GICOM/VMNAVOBJ. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVOBJ
TYPE TABLEVIEW USING SCREEN '0013'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVOBJ. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVOBJ.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVOBJ_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVOBJ.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVOBJ_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVOBJ_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVOBJ.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVOBJ_TOTAL.

*...processing: /GICOM/VMNAVOBJP................................*
TABLES: /GICOM/VMNAVOBJP, */GICOM/VMNAVOBJP. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVOBJP
TYPE TABLEVIEW USING SCREEN '0010'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVOBJP. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVOBJP.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVOBJP_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVOBJP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVOBJP_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVOBJP_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVOBJP.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVOBJP_TOTAL.

*...processing: /GICOM/VMNAVOBJT................................*
TABLES: /GICOM/VMNAVOBJT, */GICOM/VMNAVOBJT. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVOBJT
TYPE TABLEVIEW USING SCREEN '0009'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVOBJT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVOBJT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVOBJT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVOBJT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVOBJT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVOBJT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVOBJT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVOBJT_TOTAL.

*...processing: /GICOM/VMNAVTYPE................................*
TABLES: /GICOM/VMNAVTYPE, */GICOM/VMNAVTYPE. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVTYPE
TYPE TABLEVIEW USING SCREEN '0002'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVTYPE. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVTYPE.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVTYPE_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVTYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVTYPE_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVTYPE_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVTYPE.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVTYPE_TOTAL.

*...processing: /GICOM/VMNAVTYPT................................*
TABLES: /GICOM/VMNAVTYPT, */GICOM/VMNAVTYPT. "view work areas
CONTROLS: TCTRL_/GICOM/VMNAVTYPT
TYPE TABLEVIEW USING SCREEN '0003'.
DATA: BEGIN OF STATUS_/GICOM/VMNAVTYPT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMNAVTYPT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMNAVTYPT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVTYPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVTYPT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMNAVTYPT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMNAVTYPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMNAVTYPT_TOTAL.

*...processing: /GICOM/VMSRCTYPT................................*
TABLES: /GICOM/VMSRCTYPT, */GICOM/VMSRCTYPT. "view work areas
CONTROLS: TCTRL_/GICOM/VMSRCTYPT
TYPE TABLEVIEW USING SCREEN '0015'.
DATA: BEGIN OF STATUS_/GICOM/VMSRCTYPT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMSRCTYPT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMSRCTYPT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMSRCTYPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMSRCTYPT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMSRCTYPT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMSRCTYPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMSRCTYPT_TOTAL.

*...processing: /GICOM/VMUISCRN.................................*
TABLES: /GICOM/VMUISCRN, */GICOM/VMUISCRN. "view work areas
CONTROLS: TCTRL_/GICOM/VMUISCRN
TYPE TABLEVIEW USING SCREEN '0008'.
DATA: BEGIN OF STATUS_/GICOM/VMUISCRN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VMUISCRN.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VMUISCRN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMUISCRN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMUISCRN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VMUISCRN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VMUISCRN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VMUISCRN_TOTAL.

*...processing: /GICOM/VM_ADDFIG................................*
TABLES: /GICOM/VM_ADDFIG, */GICOM/VM_ADDFIG. "view work areas
CONTROLS: TCTRL_/GICOM/VM_ADDFIG
TYPE TABLEVIEW USING SCREEN '0023'.
DATA: BEGIN OF STATUS_/GICOM/VM_ADDFIG. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_ADDFIG.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_ADDFIG_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_ADDFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_ADDFIG_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_ADDFIG_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_ADDFIG.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_ADDFIG_TOTAL.

*...processing: /GICOM/VM_CH_RSA................................*
TABLES: /GICOM/VM_CH_RSA, */GICOM/VM_CH_RSA. "view work areas
CONTROLS: TCTRL_/GICOM/VM_CH_RSA
TYPE TABLEVIEW USING SCREEN '0035'.
DATA: BEGIN OF STATUS_/GICOM/VM_CH_RSA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_CH_RSA.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_CH_RSA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_CH_RSA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_CH_RSA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_CH_RSA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_CH_RSA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_CH_RSA_TOTAL.

*...processing: /GICOM/VM_CH_RSN................................*
TABLES: /GICOM/VM_CH_RSN, */GICOM/VM_CH_RSN. "view work areas
CONTROLS: TCTRL_/GICOM/VM_CH_RSN
TYPE TABLEVIEW USING SCREEN '0042'.
DATA: BEGIN OF STATUS_/GICOM/VM_CH_RSN. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_CH_RSN.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_CH_RSN_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_CH_RSN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_CH_RSN_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_CH_RSN_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_CH_RSN.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_CH_RSN_TOTAL.

*...processing: /GICOM/VM_CH_RST................................*
TABLES: /GICOM/VM_CH_RST, */GICOM/VM_CH_RST. "view work areas
CONTROLS: TCTRL_/GICOM/VM_CH_RST
TYPE TABLEVIEW USING SCREEN '0033'.
DATA: BEGIN OF STATUS_/GICOM/VM_CH_RST. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_CH_RST.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_CH_RST_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_CH_RST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_CH_RST_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_CH_RST_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_CH_RST.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_CH_RST_TOTAL.

*...processing: /GICOM/VM_FIGASS................................*
TABLES: /GICOM/VM_FIGASS, */GICOM/VM_FIGASS. "view work areas
CONTROLS: TCTRL_/GICOM/VM_FIGASS
TYPE TABLEVIEW USING SCREEN '0027'.
DATA: BEGIN OF STATUS_/GICOM/VM_FIGASS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_FIGASS.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_FIGASS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_FIGASS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_FIGASS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_FIGASS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_FIGASS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_FIGASS_TOTAL.

*...processing: /GICOM/VM_FIGDEF................................*
TABLES: /GICOM/VM_FIGDEF, */GICOM/VM_FIGDEF. "view work areas
CONTROLS: TCTRL_/GICOM/VM_FIGDEF
TYPE TABLEVIEW USING SCREEN '0028'.
DATA: BEGIN OF STATUS_/GICOM/VM_FIGDEF. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_FIGDEF.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_FIGDEF_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_FIGDEF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_FIGDEF_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_FIGDEF_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_FIGDEF.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_FIGDEF_TOTAL.

*...processing: /GICOM/VM_FIGFIT................................*
TABLES: /GICOM/VM_FIGFIT, */GICOM/VM_FIGFIT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_FIGFIT
TYPE TABLEVIEW USING SCREEN '0025'.
DATA: BEGIN OF STATUS_/GICOM/VM_FIGFIT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_FIGFIT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_FIGFIT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_FIGFIT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_FIGFIT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_FIGFIT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_FIGFIT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_FIGFIT_TOTAL.

*...processing: /GICOM/VM_GRPT..................................*
TABLES: /GICOM/VM_GRPT, */GICOM/VM_GRPT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_GRPT
TYPE TABLEVIEW USING SCREEN '0017'.
DATA: BEGIN OF STATUS_/GICOM/VM_GRPT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_GRPT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_GRPT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_GRPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_GRPT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_GRPT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_GRPT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_GRPT_TOTAL.

*...processing: /GICOM/VM_GUIDFT................................*
TABLES: /GICOM/VM_GUIDFT, */GICOM/VM_GUIDFT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_GUIDFT
TYPE TABLEVIEW USING SCREEN '0019'.
DATA: BEGIN OF STATUS_/GICOM/VM_GUIDFT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_GUIDFT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_GUIDFT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_GUIDFT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_GUIDFT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_GUIDFT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_GUIDFT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_GUIDFT_TOTAL.

*...processing: /GICOM/VM_MEFCNS................................*
TABLES: /GICOM/VM_MEFCNS, */GICOM/VM_MEFCNS. "view work areas
CONTROLS: TCTRL_/GICOM/VM_MEFCNS
TYPE TABLEVIEW USING SCREEN '0037'.
DATA: BEGIN OF STATUS_/GICOM/VM_MEFCNS. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_MEFCNS.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_MEFCNS_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_MEFCNS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_MEFCNS_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_MEFCNS_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_MEFCNS.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_MEFCNS_TOTAL.

*...processing: /GICOM/VM_MEFREC................................*
TABLES: /GICOM/VM_MEFREC, */GICOM/VM_MEFREC. "view work areas
CONTROLS: TCTRL_/GICOM/VM_MEFREC
TYPE TABLEVIEW USING SCREEN '0024'.
DATA: BEGIN OF STATUS_/GICOM/VM_MEFREC. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_MEFREC.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_MEFREC_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_MEFREC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_MEFREC_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_MEFREC_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_MEFREC.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_MEFREC_TOTAL.

*...processing: /GICOM/VM_PARROT................................*
TABLES: /GICOM/VM_PARROT, */GICOM/VM_PARROT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_PARROT
TYPE TABLEVIEW USING SCREEN '0007'.
DATA: BEGIN OF STATUS_/GICOM/VM_PARROT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_PARROT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_PARROT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_PARROT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_PARROT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_PARROT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_PARROT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_PARROT_TOTAL.

*...processing: /GICOM/VM_RMDCAT................................*
TABLES: /GICOM/VM_RMDCAT, */GICOM/VM_RMDCAT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_RMDCAT
TYPE TABLEVIEW USING SCREEN '0026'.
DATA: BEGIN OF STATUS_/GICOM/VM_RMDCAT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_RMDCAT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_RMDCAT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_RMDCAT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_RMDCAT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_RMDCAT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_RMDCAT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_RMDCAT_TOTAL.

*...processing: /GICOM/VM_RMDCTT................................*
TABLES: /GICOM/VM_RMDCTT, */GICOM/VM_RMDCTT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_RMDCTT
TYPE TABLEVIEW USING SCREEN '0022'.
DATA: BEGIN OF STATUS_/GICOM/VM_RMDCTT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_RMDCTT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_RMDCTT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_RMDCTT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_RMDCTT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_RMDCTT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_RMDCTT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_RMDCTT_TOTAL.

*...processing: /GICOM/VM_WRKSTA................................*
TABLES: /GICOM/VM_WRKSTA, */GICOM/VM_WRKSTA. "view work areas
CONTROLS: TCTRL_/GICOM/VM_WRKSTA
TYPE TABLEVIEW USING SCREEN '0020'.
DATA: BEGIN OF STATUS_/GICOM/VM_WRKSTA. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_WRKSTA.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_WRKSTA_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_WRKSTA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_WRKSTA_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_WRKSTA_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_WRKSTA.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_WRKSTA_TOTAL.

*...processing: /GICOM/VM_WRKSTT................................*
TABLES: /GICOM/VM_WRKSTT, */GICOM/VM_WRKSTT. "view work areas
CONTROLS: TCTRL_/GICOM/VM_WRKSTT
TYPE TABLEVIEW USING SCREEN '0021'.
DATA: BEGIN OF STATUS_/GICOM/VM_WRKSTT. "state vector
          INCLUDE STRUCTURE VIMSTATUS.
DATA: END OF STATUS_/GICOM/VM_WRKSTT.
* Table for entries selected to show on screen
DATA: BEGIN OF /GICOM/VM_WRKSTT_EXTRACT OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_WRKSTT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_WRKSTT_EXTRACT.
* Table for all entries loaded from database
DATA: BEGIN OF /GICOM/VM_WRKSTT_TOTAL OCCURS 0010.
INCLUDE STRUCTURE /GICOM/VM_WRKSTT.
          INCLUDE STRUCTURE VIMFLAGTAB.
DATA: END OF /GICOM/VM_WRKSTT_TOTAL.

*.........table declarations:.................................*
TABLES: /GICOM/TBAASPASS               .
TABLES: /GICOM/TBAASPDEF               .
TABLES: /GICOM/TBAASPFIG               .
TABLES: /GICOM/TBAASPFIT               .
TABLES: /GICOM/TCHG_RSN                .
TABLES: /GICOM/TCHG_RSNT               .
TABLES: /GICOM/TCNT_CHG                .
TABLES: /GICOM/TCNT_TYP                .
TABLES: /GICOM/TFOLDERT                .
TABLES: /GICOM/TGRP                    .
TABLES: /GICOM/TGRPT                   .
TABLES: /GICOM/TGUIDEDFT               .
TABLES: /GICOM/TLVL_PROT               .
TABLES: /GICOM/TMEF_CONS               .
TABLES: /GICOM/TMEF_REC                .
TABLES: /GICOM/TNAVANC                 .
TABLES: /GICOM/TNAVANCA                .
TABLES: /GICOM/TNAVANCAP               .
TABLES: /GICOM/TNAVANCT                .
TABLES: /GICOM/TNAVASS                 .
TABLES: /GICOM/TNAVASSP                .
TABLES: /GICOM/TNAVOBJ                 .
TABLES: /GICOM/TNAVOBJP                .
TABLES: /GICOM/TNAVOBJT                .
TABLES: /GICOM/TNAVTYPE                .
TABLES: /GICOM/TNAVTYPET               .
TABLES: /GICOM/TPAR_ROLT               .
TABLES: /GICOM/TRMDCAT                 .
TABLES: /GICOM/TRMDCATT                .
TABLES: /GICOM/TSRC_TYPT               .
TABLES: /GICOM/TUISCREEN               .
TABLES: /GICOM/TWRK_STA                .
TABLES: /GICOM/TWRK_STAT               .
