interface /GICOM/IF_COND_CALC_CONSTANTS
  public .


  constants CV_APLOBJ type BALOBJ_D value '/GICOM/CUSTOMIZING' ##NO_TEXT.
  constants CV_SUBOBJ_ACTIVATE type BALSUBOBJ value '/GICOM/CC_ACTIVATE' ##NO_TEXT.
  constants CV_SUBOBJ_TYPE type BALSUBOBJ value '/GICOM/CC_COND_TYPE' ##NO_TEXT.
  constants CV_SUBOBJ_GROUP type BALSUBOBJ value '/GICOM/CC_COND_GROUP' ##NO_TEXT.
  constants CV_SUBOBJ_SCHEMA type BALSUBOBJ value '/GICOM/CC_CALC_SCHEM' ##NO_TEXT.
  constants CV_SUBOBJ_PROFILE type BALSUBOBJ value '/GICOM/CC_USG_PROFIL' ##NO_TEXT.
  constants CV_SUBOBJ_VALUE_ADD type BALSUBOBJ value '/GICOM/VALUE_ADD' ##NO_TEXT.
  constants CV_SUBOBJ_VALUE_CHAIN type BALSUBOBJ value '/GICOM/VALUE_CHAIN' ##NO_TEXT.
  constants CV_TAB_COND_TYPE type TABNAME value '/GICOM/TCND_TYP' ##NO_TEXT.
  constants CV_TAB_COND_TYPE_TITLE type TABNAME value '/GICOM/TCND_TYPT' ##NO_TEXT.
  constants CV_TAB_COND_TYPE_TIT type TABNAME value '/GICOM/TCND_TIT' ##NO_TEXT.
  constants CV_TAB_COND_TYPE_CCS type TABNAME value '/GICOM/TCND_CCS' ##NO_TEXT.
  constants CV_TAB_COND_GRP type TABNAME value '/GICOM/TCNGP' ##NO_TEXT.
  constants CV_TAB_COND_GRP_TITLE type TABNAME value '/GICOM/TCNGPT' ##NO_TEXT.
  constants CV_TAB_COND_GRP_REF type TABNAME value '/GICOM/TCNGPREF' ##NO_TEXT.
  constants CV_TAB_CALC_SCHEM type TABNAME value '/GICOM/TPRPHDR' ##NO_TEXT.
  constants CV_TAB_CALC_SCHEM_TITLE type TABNAME value '/GICOM/TPRPHDRT' ##NO_TEXT.
  constants CV_TAB_CALC_SCHEM_STEP type TABNAME value '/GICOM/TPRPSTP' ##NO_TEXT.
  constants CV_TAB_CALC_SCHEM_STEP_TITLE type TABNAME value '/GICOM/TPRPSTPT' ##NO_TEXT.
  constants CV_TAB_CALC_PLAN_HDR type TABNAME value '/GICOM/CPLAN_HDR' ##NO_TEXT.
  constants CV_TAB_CALC_PLAN_INS type TABNAME value '/GICOM/CPLAN_INS' ##NO_TEXT.
  constants CV_TAB_CALC_PLAN_AGR type TABNAME value '/GICOM/CPLAN_AGR' ##NO_TEXT.
  constants CV_TAB_USG_PROF type TABNAME value '/GICOM/TUSGPF' ##NO_TEXT.
  constants CV_TAB_USG_PROF_TITLE type TABNAME value '/GICOM/TUSGPFT' ##NO_TEXT.
  constants CV_TAB_USG_PROF_POS type TABNAME value '/GICOM/TUSGPFP' ##NO_TEXT.
  constants CV_TAB_USG_PROF_POS_TITLE type TABNAME value '/GICOM/TUSGPFPT' ##NO_TEXT.
  constants CV_TAB_VALUE_ADD type TABNAME value '/GICOM/TVADEF' ##NO_TEXT.
  constants CV_TAB_VALUE_ADD_TEXT type TABNAME value '/GICOM/TVADEFT' ##NO_TEXT.
  constants CV_TAB_VALUE_ADD_REFERENCE type TABNAME value '/GICOM/TVAREF' ##NO_TEXT.
  constants CV_TAB_VALUE_CHAIN type TABNAME value '/GICOM/TVACDEF' ##NO_TEXT.
  constants CV_TAB_VALUE_CHAIN_TEXT type TABNAME value '/GICOM/TVACDEFT' ##NO_TEXT.
  constants CV_TAB_VALUE_CHAIN_REFERENCE type TABNAME value '/GICOM/TVACREF' ##NO_TEXT.
  constants CV_MESSAGE_ID type SY-MSGID value '/GICOM/MSG_COND_CALC' ##NO_TEXT.
  constants CV_VALUE_ADD_ROOT type /GICOM/VALUE_ADD_ID value 'ROOT' ##NO_TEXT.
  constants CV_VALUE_ADD_CONSUMER type /GICOM/VALUE_ADD_ID value 'CNMR' ##NO_TEXT.
endinterface.
