interface /GICOM/IF_CONST_AGRMT_STATUS
  public .


  CONSTANTS GC_AGRMT_STATUS_IN_PREPARATION TYPE /GICOM/STATUS_AGRMT Value 'A'.
  CONSTANTS GC_AGRMT_STATUS_ACTIVE         TYPE /GICOM/STATUS_AGRMT Value 'B'.
  CONSTANTS GC_AGRMT_STATUS_INVALID        TYPE /GICOM/STATUS_AGRMT Value 'C'.
  CONSTANTS GC_AGRMT_STATUS_IN_PLANNING    TYPE /GICOM/STATUS_AGRMT Value 'D'.
  CONSTANTS GC_AGRMT_STATUS_ONLY_REFBASE   TYPE /GICOM/STATUS_AGRMT Value 'R'.
endinterface.
